# Values for github-actions-cache-server.
# This is a YAML-formatted file.

replicaCount: 2

strategy:
  type: Recreate

image:
  repository: ghcr.io/falcondev-oss/github-actions-cache-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /
    port: cache
readinessProbe:
  httpGet:
    path: /
    port: cache

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

persistentVolumeClaim:
  enabled: false
  template:
    metadata:
      name: cache-data
      labels: {}
      annotations: {}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem
      storageClassName: "local-path"

tmpVolume:
  ephemeral:
    volumeClaimTemplate:
      metadata:
        labels:
          type: github-actions-cache-server-tmp
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 2Gi

env:
  - name: DEBUG
    value: "false"

  - name: DB_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cache-postgres-postgresql
        key: postgres-password

  - name: DB_POSTGRES_USER
    value: "postgres"

  - name: DB_POSTGRES_DATABASE
    value: "actions_cache"

  - name: DB_POSTGRES_HOST
    value: "cache-postgres-postgresql"

  - name: DB_POSTGRES_PORT
    value: "5432"

  - name: DB_DRIVER
    value: "postgres"

  - name: STORAGE_DRIVER
    value: "s3"

  - name: STORAGE_S3_BUCKET
    value: "sccache"

  - name: AWS_ENDPOINT_URL
    value: "http://minio-sccache:9000"

  - name: AWS_ACCESS_KEY_ID
    value: aaa

  - name: AWS_SECRET_ACCESS_KEY
    value: aaa

  - name: CACHE_CLEANUP_OLDER_THAN_DAYS
    value: "10"

  - name: ENABLE_DIRECT_DOWNLOADS
    value: "true"
