## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg or https://github.com/enterprises/myenterprise
githubConfigUrl: "https://github.com/nponsard/cache-thing"
githubConfigSecret: pre-defined-secret

maxRunners: 3
minRunners: 1

# runnerGroup: Ariel

## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    containers:
      - name: runner
        image: docker.io/sautax/ariel-build-image:0.7
        command: ["/home/runner/run.sh"]
        env:
          # Move cargo home so it can be cached.
          - name: CARGO_HOME
            value: /home/runner/.cargo
          - name: SCCACHE_DIR
            value: /mnt/sccache
          - name: SCCACHE_CACHE_SIZE
            value: "300G"
          - name: RUSTC_WRAPPER
            value: sccache
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
        # mount the local cache, it is not shared between nodes
        volumeMounts:
          - mountPath: /cache/
            name: sccache
    # topologySpreadConstraints:
    #   - maxSkew: 1
    #     topologyKey: "kubernetes.io/hostname"
    #     whenUnsatisfiable: ScheduleAnyway
    #     labelSelector:
    #       matchLabels:
    #         actions-ephemeral-runner: "True"
    nodeSelector:
      kubernetes.io/hostname: tribe-ariel-ci1
    volumes:
      - name: sccache
        hostPath:
          path: /cache/ # directory location on host
