## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg or https://github.com/enterprises/myenterprise
githubConfigUrl: "https://github.com/ariel-os"
githubConfigSecret: pre-defined-secret

maxRunners: 20
minRunners: 10

runnerGroup: Ariel

# containerMode:
#   type: "kubernetes"  ## type can be set to dind or kubernetes
#   ## the following is required when containerMode.type=kubernetes
#   kubernetesModeWorkVolumeClaim:
#     accessModes: ["ReadWriteOnce"]
#     # For local testing, use https://github.com/openebs/dynamic-localpv-provisioner/blob/develop/docs/quickstart.md to provide dynamic provision volume with storageClassName: openebs-hostpath
#     storageClassName: "local-path"
#     resources:
#       requests:
#         storage: 1Gi

## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    containers:
      - name: runner
        image: docker.io/sautax/ariel-build-image:0.6
        command: ["/home/runner/run.sh"]
        env:
          # Move cargo home so it can be cached.
          - name: CARGO_HOME
            value: /home/runner/.cargo
          - name: SCCACHE_DIR
            value: /cache/sccache
          - name: SCCACHE_CACHE_SIZE
            value: "100G"
          - name: RUSTC_WRAPPER
            value: sccache
          # - name: CUSTOM_ACTIONS_RESULTS_URL
          #   value: http://action-cache-github-actions-cache-server.arc-runners.svc.cluster.local/
          # - name: ACTIONS_RESULTS_URL
          #   value: http://action-cache-github-actions-cache-server.arc-runners.svc.cluster.local/
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
        # mount the local cache, it is not shared between nodes
        volumeMounts:
          - mountPath: /cache
            name: sccache
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            actions-ephemeral-runner: "True"
    volumes:
      - name: sccache
        hostPath:
          path: /cache # directory location on host
          